# source "~/.local/lib/python3.9/site-packages/powerline/bindings/tmux/powerline.conf"
# source-file "./flexoki-light.tmuxtheme"
source-file "~/dev.tmux.conf"

bind r source-file ~/.tmux.conf

setw -g mouse on
set-option -g prefix C-a
set -g status-right '#T'
set-option -g allow-rename off
set -g base-index 1
set -s escape-time 0
setw -g mode-keys vi
set -s copy-command 'xclip -selection clipboard'
set -g extended-keys on
set -g extended-keys-format csi-u

# switch panes using Alt+Left/Right/Up/Down without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch panes using Alt+h/j/k/l without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-n next-window

# Split pane vertically in current directory
bind v split-window -v -c "#{pane_current_path}"

# Split pane horizontally in current directory
bind h split-window -h -c "#{pane_current_path}"

set -g focus-events on
