[tools]
aqua = "latest"
"aqua:asciinema/agg" = "latest"
"aqua:asciinema/asciinema" = "latest"
biome = "latest"
bun = "latest"
crystal = "latest"
dotnet = "latest"
erlang = "latest"
"github:badlogic/pi-mono" = "latest"
"github:bjarneo/cliamp" = "latest"
haskell = "latest"
helm = "latest"
janet = "latest"
julia = "latest"
k3d = "latest"
kind = "latest"
kotlin = { version = "latest", asset_pattern = "kotlin-compiler-*.zip", bin_path = "kotlinc/bin" }
lima = "latest"
minikube = "latest"
nim = "latest"
node = "latest"
ollama = "latest"
opam = { version = "latest", asset_pattern = "opam-*-{gnu_arch}-{os}" }
podman = { version = "latest", rename_exe = "podman", bin = "podman" }
racket = "latest"
raku = "latest"
resvg = "latest"
ruby = "latest"
rust = "latest"
swiprolog = "latest"
uv = "latest"
yarn = "latest"
zig = "latest"
elixir = "latest"
ansible = { version = "latest", pipx_args = "--include-deps", uvx = "false" }
v = "weekly.2026.08"
pulumi = "latest"
"aqua:block/goose" = "latest"
unison = "release/1.2.0"
"github:timescale/tigerfs" = "latest"
television = "latest"
bat = "latest"
"aqua:nushell/nushell" = "latest"
fd = "latest"
difftastic = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
k6 = "latest"
go = "latest"
tmux = "latest"
rg = "latest"
lazygit = "latest"
k9s = "latest"
yq = "latest"
typst = "latest"
tree-sitter = "latest"
zoxide = "latest"
yazi = "latest"
"aqua:peteretelej/tree" = "1.3.0"
opentofu = "latest"
opencode = "latest"
fzf = "latest"
duf = "latest"
pnpm = "latest"
vscode-insiders = "latest"
dmd = "nightly"
odin = "latest"
"aqua:syncthing/syncthing" = "latest"
maven = "latest"
neovim = "latest"
docker-compose = "latest"

[env]
MISE_DISABLE_TOOLS = "python"

[settings]
minimum_release_age = "0s"
minimum_release_age_excludes = ["asdf:*", "aqua:*", "github:*", "*"]
